webtalk_init -webtalk_dir D:\\Vivado\\CounterCode\\top_cymometer.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-08-13 14:02:38" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "roscluvmbhc8am17t3rrrv06a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.868 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1786600415343" -context "sdk\\\\bsp/1786600415343"
webtalk_add_data -client sdk -key hwid -value "1786538095425" -context "sdk\\\\bsp/1786600415343"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1786600415343"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1786600415343"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1786600415343"
webtalk_add_data -client sdk -key uid -value "1786600421713" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key hwid -value "1786538095425" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key bspid -value "1786600415343" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key projSize -value "594.890625" -context "sdk\\\\application/1786600421713"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key BootgenCount -value "1" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1786600958833"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1786600958833"
webtalk_transmit -clientid 1615195953 -regid "" -xml D:\\Vivado\\CounterCode\\top_cymometer.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Vivado\\CounterCode\\top_cymometer.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Vivado\\CounterCode\\top_cymometer.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
