#=============================================================================
# Counter_Core v1.0 repackaging script
#
# The new architecture adds 5 source files and 4 differential clock ports, and
# changes M_AXIS from 32 to 64 bits wide. All of that has to be reflected in
# component.xml; editing the XML by hand is easy to get wrong, so this script
# lets Vivado infer it.
#
# Usage (Vivado Tcl Console, Vivado 2018.3):
#   cd D:/Vivado/CounterCode/ip_repo/Counter_Core/Counter_Core_1.0
#   source package_ip.tcl
#
# The script opens the IP Packager project edit_Counter_Core_v1_0.xpr, adds
# the new sources, merges the changes and saves component.xml. Afterwards, in
# the main project:
#   1. Refresh IP Catalog
#   2. Re-add Counter_Core to the BD, or Upgrade IP on the existing instance
#   3. Change the stream width of axis_data_fifo_0 and axi_dma_0 to 64
#
# Note: this script has not been run and verified. Watch the Console on the
# first execution.
#=============================================================================

set ip_root  [file normalize [file dirname [info script]]]
set edit_prj [file normalize "$ip_root/../edit_Counter_Core_v1_0.xpr"]

if {![file exists $edit_prj]} {
    error "IP Packager project not found: $edit_prj"
}

# Close any already-open project so add_files cannot land in the wrong fileset
catch { close_project }
open_project $edit_prj

#-----------------------------------------------------------------------------
# 1. Add the new source files
#
# Layout follows the convention of the previous IP: hdl/ holds the AXI
# interface layer generated by the packager, src/ holds the measurement core.
#
# Order does not matter; Vivado resolves the hierarchy itself. cdc.v contains
# the three modules rst_sync / bit_sync / cnt_cdc, shared by counter_core,
# ts_engine and eq_counter.
#-----------------------------------------------------------------------------
set new_srcs [list \
    "$ip_root/src/cdc.v" \
    "$ip_root/src/tdc.v" \
    "$ip_root/src/ts_engine.v" \
    "$ip_root/src/eq_counter.v" \
    "$ip_root/src/counter_core.v" \
]

foreach f $new_srcs {
    if {![file exists $f]} { error "missing source file: $f" }
}

add_files -norecurse -fileset sources_1 $new_srcs
update_compile_order -fileset sources_1

# Simulation source (optional, not part of synthesis)
set tb "$ip_root/sim/tb_counter_core.v"
if {[file exists $tb]} {
    add_files -norecurse -fileset sim_1 $tb
    set_property top tb_counter_core [get_filesets sim_1]
    update_compile_order -fileset sim_1
}

#-----------------------------------------------------------------------------
# 2. Merge project changes into component.xml
#-----------------------------------------------------------------------------
set core [ipx::current_core]

ipx::merge_project_changes files      $core
ipx::merge_project_changes hdl_parameters $core
ipx::merge_project_changes ports      $core

#-----------------------------------------------------------------------------
# 3. M_AXIS width 32 -> 64
#
# Timestamps are a fixed 64 bits each, matching the PS HP0 port width so no
# upsizer is required.
#-----------------------------------------------------------------------------
set tdata_param [ipx::get_user_parameters C_M_AXIS_TDATA_WIDTH -of_objects $core]
if {[llength $tdata_param]} {
    set_property value 64 $tdata_param
    set_property value_format long $tdata_param
}

set tdata_hdl [ipx::get_hdl_parameters C_M_AXIS_TDATA_WIDTH -of_objects $core]
if {[llength $tdata_hdl]} {
    set_property value 64 $tdata_hdl
}

#-----------------------------------------------------------------------------
# 4. Group the differential clock ports
#
# Makes clk_fs_p/n and clk_fx_p/n appear as differential pairs in the BD so
# they are harder to wire backwards.
#-----------------------------------------------------------------------------
foreach {pair pin_p pin_n} {
    clk_fs clk_fs_p clk_fs_n
    clk_fx clk_fx_p clk_fx_n
} {
    if {[llength [ipx::get_ports $pin_p -of_objects $core]]} {
        set bif [ipx::add_bus_interface $pair $core]
        set_property abstraction_type_vlnv \
            xilinx.com:interface:diff_clock_rtl:1.0 $bif
        set_property bus_type_vlnv \
            xilinx.com:interface:diff_clock:1.0 $bif
        set_property interface_mode slave $bif

        set map_p [ipx::add_port_map CLK_P $bif]
        set_property physical_name $pin_p $map_p
        set map_n [ipx::add_port_map CLK_N $bif]
        set_property physical_name $pin_n $map_n
    }
}

#-----------------------------------------------------------------------------
# 5. Tag stream_aresetn as a reset interface
#
# Without this it packages as a plain output and the BD will not offer it as
# a reset source. Polarity must be declared too, otherwise Vivado assumes
# active high and inverts it during connection automation.
#-----------------------------------------------------------------------------
if {[llength [ipx::get_ports stream_aresetn -of_objects $core]]} {
    set rst_if [ipx::add_bus_interface stream_aresetn $core]
    set_property abstraction_type_vlnv xilinx.com:signal:reset_rtl:1.0 $rst_if
    set_property bus_type_vlnv         xilinx.com:signal:reset:1.0     $rst_if
    set_property interface_mode        master                          $rst_if

    set rst_map [ipx::add_port_map RST $rst_if]
    set_property physical_name stream_aresetn $rst_map

    set_property value ACTIVE_LOW \
        [ipx::add_bus_parameter POLARITY $rst_if]
}

#-----------------------------------------------------------------------------
# 6. Generate the GUI, update checksums and save
#-----------------------------------------------------------------------------
ipx::create_xgui_files $core
ipx::update_checksums  $core
ipx::check_integrity   $core
ipx::save_core         $core

puts "=========================================================="
puts " Counter_Core packaged: $ip_root/component.xml"
puts ""
puts " Next steps:"
puts "   0. In the BD, connect Counter_Core_0/stream_aresetn to"
puts "      axis_data_fifo_0/s_axis_aresetn (replacing the global reset)"
puts "   1. Main project IP Catalog -> Refresh"
puts "   2. Upgrade or re-add Counter_Core in the BD"
puts "   3. Set axis_data_fifo_0 / axi_dma_0 stream width to 64"
puts "   4. Add create_clock constraints for clk_fs / clk_fx in the XDC"
puts "=========================================================="
